FROM ubuntu:20.04

MAINTAINER Fernando Aguilar "aguilarf@ifca.unican.es"

RUN apt-get update -y && \
    apt-get install -y curl python3-pip python3-dev git vim lsof

RUN grep -R "dspace_7" .
RUN git clone https://github.com/EOSC-synergy/FAIR_eva.git

WORKDIR /FAIR_eva
RUN grep -R "dspace_7" .

RUN pip3 install -r requirements.txt

EXPOSE 5000 9090
RUN cp config.ini.template config.ini
RUN cd /FAIR_eva
RUN chmod 777 start.sh
RUN cat start.sh
CMD /FAIR_eva/start.sh
